server:
  port: 8081
  servlet:
    context-path: /

spring:
  # Redis Configuration
  redis:
    host: redis
    port: 6379
  
  # Redis Repositories Configuration
  data:
    redis:
      repositories:
        enabled: false  # Disable Redis repositories
    
  # Database Configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/fleetdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

# Logging Configuration
logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized